spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/realty
        username: postgres
        password: root
        hikari:
            schema: realty
    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: validate

server:
    port: 8189



