 create table real_estate (
        dtype varchar(31) not null,
        id int8 generated by default as identity,
        city varchar(255) not null,
        house_number varchar(255) not null,
        is_deleted boolean default false,
        price numeric(19, 2) not null,
        street varchar(255) not null,
        total_area float8 not null,
        floor_number int4,
        number_of_rooms int4,
        house_type varchar(255),
        land_area float8,
        primary key (id)
);
 create table roles(
         id int8 generated by default as identity,
         name varchar(255),
         primary key (id)
 );
 create table user_roles (
         user_id int8 not null,
         role_id int8 not null
 );
 create table users (
         id int8 generated by default as identity,
         password varchar(255),
         username varchar(255) unique,
         primary key (id)
 );

alter table if exists user_roles add foreign key (role_id) references roles;

 alter table if exists user_roles add foreign key (user_id) references users;